package generator

import (
	"github.com/nicolerobin/zrpc/cmds/protoc-gen-zrpc/constant"
	"google.golang.org/protobuf/cmd/protoc-gen-go/internal_gengo"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

const (
	errorsPackage       = "errors"
	contextPackage      = "context"
	ioPackage           = "io"
	syncPackage         = "sync"
	grpcPackage         = "google.golang.org/grpc"
	grpcStatusPackage   = "google.golang.org/grpc/status"
	grpcCodesPackage    = "google.golang.org/grpc/codes"
	grpcMetadataPackage = "google.golang.org/grpc/metadata"
	protoPackage        = "google.golang.org/protobuf/proto"
	clientPackage       = protogen.GoImportPath("github.com/nicolerobin/zrpc/client")
	serverPackage       = protogen.GoImportPath("github.com/nicolerobin/zrpc/server")
	rpcPackage          = protogen.GoImportPath("github.com/nicolerobin/zrpc/core/rpc")
)

func Generate() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, f := range gen.Files {
			if f.Generate {
				genFile(gen, f)
			}
		}
		return nil
	})
}

func genFile(gen *protogen.Plugin, f *protogen.File) {
	genGo(gen, f)
	genRpc(gen, f)
}

func genGo(gen *protogen.Plugin, file *protogen.File) {
	internal_gengo.GenerateFile(gen, file)
}

func genRpc(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Services) == 0 {
		return
	}

	name := file.GeneratedFilenamePrefix + "_grpc.pb.go"
	generatedFile := gen.NewGeneratedFile(name, file.GoImportPath)

	generatedFile.P("// Code generated by protoc-gen-zrpc. DO NOT EDIT.")
	generatedFile.P("//")
	generatedFile.P("// version: protoc-gen-zrpc ", constant.Version)
	generatedFile.P("// source: ", file.Desc.Path())
	generatedFile.P()
	generatedFile.P("package ", file.GoPackageName)

	pkgName := string(file.Desc.Package())
	clientGetter := generatedFile.QualifiedGoIdent(rpcPackage.Ident("ClientGetter"))
	serverRegister := generatedFile.QualifiedGoIdent(serverPackage.Ident("RegisterService"))

	for _, service := range file.Services {
		r := serviceRender{
			service:        service,
			pkgName:        pkgName,
			fileName:       service.Desc.ParentFile().Path(),
			clientGetter:   clientGetter,
			serverRegister: serverRegister,
			qualified:      generatedFile.QualifiedGoIdent,
		}

		generatedFile.P(r.render())
		generatedFile.P()
	}
}
